version: '3.1'

services:
  php:
    build: .
    container_name: PHP-Apache
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    container_name: MySQL
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ''